spring.application.name=Resume-analyser

server.port=${PORT:8080}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${url}
spring.datasource.username=${uname}
spring.datasource.password=${upass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

apiKey=${mailkey}
genKey=${genkey}

spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

spring.security.oauth2.client.registration.google.client-id=${gcpid}
spring.security.oauth2.client.registration.google.client-secret=${gcpsecret}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

application-id=${adzunaid}
application-api-key=${adzunakey}

jwt-key=${jwtkey}

app.cookie.secure=${COOKIE_SECURE:false}

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=WARN

mail.sender=your-verified-brevo-email@gmail.com
mail.sender-name=Resume Analyser
